// components/Layout.js
import Head from "next/head";
import Header from "./Header";  // Import the Header component
import styles from "@/styles/Home.module.css";

type Props = {  // Define a Props type
    children: React.ReactNode;
};

export default function Layout({children}: Props) {
    return (
        <>
            <Head>
                <title>WalletConnect | Next Starter Template</title>
                <meta
                    name="description"
                    content="Generated by create-wc-dapp"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.headerClass}>
                <Header />
            </div>
            <main className={styles.main}>
                <div className={styles.wrapper}>
                    {children}
                </div>
            </main>
        </>
    );
}
